site_url: https://blog.danielxxf.site
display_url: https://blog.danielxxf.site
publish_mode: editorial_workflow
show_preview_links: true
backend:
  name: github
  repo: Danielxxf/my-blog
  branch: main
  base_url: https://blog.danielxxf.site
  auth_endpoint: /api/auth
  squash_merges: true
  preview_context: 'cloudflare preview deploy'
media_folder: "static/img"
public_folder: "/img"
collections:
  - name: articles
    label: Articles
    folder: "content/post"
    create: true
    slug: "{{slug}}"
    preview_path: '{{slug}}'
    nested:
      depth: 100 # max depth to show in the collection tree
      summary: '{{title}}' # optional summary for a tree node, defaults to the inferred title field
    editor:
      preview: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Categories", name: "categories", widget: "list", allow_add: true, required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: categories
    label: Categories
    folder: "content/categories"
    create: true
    slug: "{{slug}}"
    preview_path: '{{slug}}'
    nested:
      depth: 100 # max depth to show in the collection tree
      summary: '{{title}}' # optional summary for a tree node, defaults to the inferred title field
    editor:
      preview: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - label: "Style" 
        name: "style"
        widget: "object"
        required: false, 
        fields:
          - { label: Background, name: background, widget: color, required: false}
          - { label: Color, name: color, widget: color, required: false}