site_url: https://blog.danielxxf.site
display_url: https://blog.danielxxf.site
publish_mode: editorial_workflow
show_preview_links: true
backend:
  name: github
  repo: Danielxxf/my-blog
  branch: main
  base_url: https://blog.danielxxf.site
  auth_endpoint: /api/auth
  squash_merges: true
  preview_context: 'cloudflare preview deploy'
media_folder: "static/uploads"
public_folder: "/uploads"
collections:
  - name: articles
    label: Articles
    folder: "content/articles"
    create: true
    slug: "{{slug}}"
    preview_path: '{{slug}}'
    editor:
      preview: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }